# Reshifr Hash Index
# NMake

CL = cl
LINK = link

FLAGS = /O2
RHI_FLAGS = /Wall /DRHI_PRIME_METHODX
TEST_FLAGS =

RHI_DIR = ..\src
TEST_DIR = .
BUILD_DIR = build

INCLUDES = /I$(RHI_DIR)
LIBS =
TARGET = tests.exe

RHI_HEADERS = \
	$(RHI_DIR)\rhi.h

TEST_HEADERS = \
	$(TEST_DIR)\tests.h

HEADERS = $(RHI_HEADERS) $(TEST_HEADERS)

OBJS = \
	$(BUILD_DIR)\rhi.obj \
	$(BUILD_DIR)\tests.obj \
	$(BUILD_DIR)\utils.obj \
	$(BUILD_DIR)\set_init.obj \
	$(BUILD_DIR)\set_reserve.obj \
	$(BUILD_DIR)\set_insert.obj \
	$(BUILD_DIR)\set_search.obj \
	$(BUILD_DIR)\set_replace.obj \
	$(BUILD_DIR)\set_kreplace.obj

all: $(OBJS) $(TARGET)

clean:
	del $(OBJS) $(TARGET)

# Compile the source on the src directory
#
$(BUILD_DIR)\rhi.obj: $(RHI_DIR)\rhi.c $(RHI_HEADERS)
	$(CL) /c $(RHI_DIR)\rhi.c /Fo:$@ $(FLAGS) $(RHI_FLAGS) $(INCLUDES)

# Compile the source on the tests directory
#
$(BUILD_DIR)\tests.obj: $(TEST_DIR)\tests.c $(HEADERS)
	$(CL) /c $(TEST_DIR)\tests.c /Fo:$@ $(FLAGS) $(TEST_FLAGS) $(INCLUDES)

$(BUILD_DIR)\utils.obj: $(TEST_DIR)\utils.c $(HEADERS)
	$(CL) /c $(TEST_DIR)\utils.c /Fo:$@ $(FLAGS) $(TEST_FLAGS) $(INCLUDES)

# Compile the source on the tests\set directory
#
$(BUILD_DIR)\set_init.obj: $(TEST_DIR)\set\init.c $(HEADERS)
	$(CL) /c $(TEST_DIR)\set\init.c /Fo:$@ $(FLAGS) $(TEST_FLAGS) $(INCLUDES)

$(BUILD_DIR)\set_reserve.obj: $(TEST_DIR)\set\reserve.c $(HEADERS)
	$(CL) /c $(TEST_DIR)\set\reserve.c /Fo:$@ $(FLAGS) $(TEST_FLAGS) $(INCLUDES)

$(BUILD_DIR)\set_insert.obj: $(TEST_DIR)\set\insert.c $(HEADERS)
	$(CL) /c $(TEST_DIR)\set\insert.c /Fo:$@ $(FLAGS) $(TEST_FLAGS) $(INCLUDES)

$(BUILD_DIR)\set_search.obj: $(TEST_DIR)\set\search.c $(HEADERS)
	$(CL) /c $(TEST_DIR)\set\search.c /Fo:$@ $(FLAGS) $(TEST_FLAGS) $(INCLUDES)

$(BUILD_DIR)\set_replace.obj: $(TEST_DIR)\set\replace.c $(HEADERS)
	$(CL) /c $(TEST_DIR)\set\replace.c /Fo:$@ $(FLAGS) $(TEST_FLAGS) $(INCLUDES)

$(BUILD_DIR)\set_kreplace.obj: $(TEST_DIR)\set\kreplace.c $(HEADERS)
	$(CL) /c $(TEST_DIR)\set\kreplace.c /Fo:$@ $(FLAGS) $(TEST_FLAGS) $(INCLUDES)

# Create executable
#
$(TARGET): $(OBJS)
	$(LINK) $(OBJS) /OUT:$(TARGET)
