# Reshifr Hash Index
# Github Actions

name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: sh
        working-directory: tests
    steps:
      - uses: actions/checkout@v2
      - name: Package Preparation
        run: |
          sudo apt-get update
          sudo apt-get install gcc-multilib g++-multilib clang
      - name: GCC x86
        run: |
          make -j \
            -e 'FLAGS = -DRHI_PRIME' \
            -e 'CC = gcc -m32' \
            -e 'CXX = g++ -m32' run
          make clean
      - name: GCC x64
        run: |
          make -j \
            -e 'FLAGS = -DRHI_PRIME' \
            -e 'CC = gcc -m64' \
            -e 'CXX = g++ -m64' run
          make clean
      - name: Clang x86
        run: |
          make -j \
            -e 'FLAGS = -DRHI_PRIME' \
            -e 'CC = clang -m32' \
            -e 'CXX = clang++ -m32' run
          make clean
      - name: Clang x64
        run: |
          make -j \
            -e 'FLAGS = -DRHI_PRIME' \
            -e 'CC = clang -m64' \
            -e 'CXX = clang++ -m64' run
          make clean
  macos:
    runs-on: macos-latest
    defaults:
      run:
        shell: sh
        working-directory: tests
    steps:
      - uses: actions/checkout@v2
      - name: Clang
        run: |
          make -j \
            -e 'FLAGS = -DRHI_PRIME' \
            -e 'CC = clang' \
            -e 'CXX = clang++' run
          make clean
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
        working-directory: tests
    steps:
      - uses: actions/checkout@v2
      - name: Set up MSVC x86
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - name: MSVC x86
        run: |
          nmake /F Makefile.msc /E "FLAGS = /DRHI_PRIME" run
          nmake /F Makefile.msc clean
      - name: Set up MSVC x64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: MSVC x64
        run: |
          nmake /F Makefile.msc /E "FLAGS = /DRHI_PRIME" run
          nmake /F Makefile.msc clean
