name: Testing

on:
  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

defaults:
  run:
    working-directory: ./tests
    
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: |
          make
